add contribute-docs article
karmada-io/website pull request #145
Opened 2022-08-25 09:35 UTC by Poor12

Signed-off-by: Poor12 <shentiecheng@huawei.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Since we move our docs to our website, we need a docs to guide users how to contribute docs.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
cc @RainbowMango

2022-08-31 09:06 UTC, Arhell reviewed
/assign @RainbowMango

2022-09-01 01:33 UTC, rgrupesh reviewed
@Poor12 I think we should also add `setting up local environment section`.

2022-09-01 01:45 UTC, rgrupesh commented
> > @Poor12 I think we should also add `setting up local environment section`.
> 
> Thanks. I'm a little confused about what you mean `setting up local environment section`

Like the prerequisite steps that contributor need to follow to clone the repository locally(on their machine) and contribute to it. In my view, if it detailed in the `contribute docs` it would help to avoid conflict in the future.

2022-09-01 01:47 UTC, Poor12 commented
Oh，I get it. Thanks for reminding.

2022-09-24 07:00 UTC, Poor12 commented
/cc @RainbowMango

2022-09-24 08:38 UTC, RainbowMango commented on docs/contributor/contribute-docs.md
> +title: How to contribute docs
@Tingtal Could you please take a look at this doc? you can get the preview at :
https://deploy-preview-145--karmada.netlify.app/docs/next/contributor/contribute-docs

2022-09-29 03:12 UTC, Tingtal requested changes
Small touches on the language

2022-09-29 03:12 UTC, Tingtal commented on docs/contributor/contribute-docs.md
> +  Then Add the corresponding Chinese content to the Chinese directory.
```suggestion
  Then add the corresponding Chinese content to the Chinese directory.
```

2022-09-29 03:12 UTC, Tingtal commented on docs/contributor/contribute-docs.md
> +Now you have already completed docs. After you start a PR to `karmada.io/website`, if you have passed CI, you can preview the effect of your document on the website.
```suggestion
Now you have already completed docs. After you start a PR to `karmada.io/website`, if you have passed CI, you can get a preview of your document on the website.
```

2022-09-29 03:12 UTC, Tingtal commented on i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
> +| Trip.com                  | https://www.trip.com/   | Build a more resilient and elastic hybrid-multi-cloud platform using Karmada          | TBD
```suggestion
| Trip.com                  | https://www.trip.com/   | Build a more resilient and elastic hybrid & multi-cloud platform using Karmada          | TBD                                                                           |
```

2022-09-29 03:12 UTC, Tingtal commented on i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
>  | Youzan                    | https://www.youzan.com/ | Manage both Stateless and Stateful on-line workloads across multiple clusters         | TBD
```suggestion
| Youzan                    | https://www.youzan.com/ | Manage both stateless and stateful online workloads across multiple clusters         | TBD                                                                           |
```

2022-10-08 09:00 UTC, RainbowMango approved these changes
/lgtm
/approve

2022-10-08 09:01 UTC, merged