Add docs for LabelsOverrider/AnnotationsOverrider
karmada-io/website pull request #213
Opened 2022-10-20 07:16 UTC by chaunceyjiang

Signed-off-by: chaunceyjiang <chaunceyjiang@gmail.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add docs for LabelsOverrider/AnnotationsOverrider
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

2022-10-20 07:28 UTC, Arhell reviewed
/assign @RainbowMango

2022-10-20 07:37 UTC, RainbowMango commented
Generally looks good to me. Please @Tingtal help to review it from a grammar point.

2022-10-28 11:27 UTC, Tingtal requested changes
Language check.

2022-10-28 11:27 UTC, Tingtal commented on docs/userguide/scheduling/override-policy.md
> +- `add`: the items in `value` will be appended to labels.
```suggestion
- `add`: The items in `value` will be appended to labels.
```

2022-10-28 11:27 UTC, Tingtal commented on docs/userguide/scheduling/override-policy.md
> +- `remove`: if the item in `value` matches the item in labels, it will be deleted. If it does not match, nothing will be done.
```suggestion
- `remove`: If the item in `value` matches the item in labels, the former will be deleted. If they do not match, nothing will be done.
```

2022-10-28 11:27 UTC, Tingtal commented on docs/userguide/scheduling/override-policy.md
> +- `replace`: if the key in `value` matches the key in the label, it will be replaced. If it does not match, it will not do anything
```suggestion
- `replace`: If the key in `value` matches the key in the label, the former will be replaced. If they do not match, nothing will be done.
```

2022-10-28 11:27 UTC, Tingtal commented on docs/userguide/scheduling/override-policy.md
> +Note: the usage of `AnnotationsOverrider` is similar to `LabelsOverrider`, You can refer to the `LabelsOverrider` examples.
```suggestion
Note: `AnnotationsOverrider` functions the similar way as `LabelsOverrider`. You can refer to the `LabelsOverrider` examples.
```

2022-10-31 07:30 UTC, RainbowMango approved these changes
/lgtm
/approve

2022-10-31 07:30 UTC, merged