Add test report for Karmada1.3
karmada-io/website pull request #220
Opened 2022-10-26 02:26 UTC by Poor12

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add test report for Karmada1.3

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
None

2022-10-29 03:28 UTC, Poor12 commented
/cc @Tingtal

2022-10-31 08:56 UTC, Tingtal requested changes
Language check.

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +   In fact, API objects in a single cluster also include common objects such as service, configmap, secret and so on. The introduction of these variables will make the testing process more complicate
```suggestion
   In fact, API objects in a single cluster also include common objects such as Services, ConfigMaps, secrets and so on. The introduction of these variables will make the testing process more complicated, so this test does not focus too much on the above variables.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +Dimensions are sometimes not independent. As you move farther along one dimension, your cross-section wrt other dimensions gets smaller.
```suggestion
Dimensions are interactive. One weighs more, the rest weigh less.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +Taking the two dimensions of #Num of Clusters and #Num of Nodes as an example, in the scenario of stretching 5k nodes in a single cluster to 10k nodes under 100 clusters, or expanding the number of c
```suggestion
Take the dimensions #Num of Clusters and #Num of Nodes as an example. When scaling from 5k nodes to 10k in 100 individual clusters, or expanding to 200 clusters while maintaining the original size of each cluster, the specifications of other dimensions will be surely affected.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +3. Cluster Register Latency
```suggestion
3. Cluster Registration Latency
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +4. Resource usage
```suggestion
4. Resource Usage
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +1. The metrics measured do not account for network fluctuations between the control plane and member clusters. Also, Intra-cluster SLOs are not taken into account.
```suggestion
1. Network fluctuations between the control plane and member clusters, as well as intra-cluster SLOs, are not taken into account for the metrics measured.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +3. Cluster Register Latency contains the duration from when the cluster is registered in the control plane to when the cluster becomes available.
```suggestion
3. Cluster Registration Latency contains the duration from when the cluster is registered in the control plane to when the cluster becomes available.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +Prometheus is a systems and service monitoring system. It collects metrics from configured targets at given intervals, evaluates rule expressions, displays the results, and can trigger alerts when sp
```suggestion
Prometheus is a system and service monitoring system. It collects metrics from configured targets at given intervals, evaluates rule expressions, displays the results, and triggers alerts when specified conditions are observed. After analyzing the processing of indicators by ClusterLoader2, we use Prometheus to monitor various indicators of the control plane according to specific query statements.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +Cluster register latency:
```suggestion
Cluster registration latency:
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +In the process of Pull mode cluster registration, it will include the installation time of Karmada-agent in the member cluster. When the image of karmada-agent is ready, it will depend on the latency
```suggestion
In the process of cluster registration in Pull mode, the latency will include the installation time of Karmada-agent in the member cluster. When the image of karmada-agent is ready, the latency depends on that of Pod startup in a single cluster.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +Karmada-agent in the member cluster with 5k Node and 2w Pod costs 40m CPU(cores) and 266Mi Memory(bytes).
```suggestion
Karmada-agent in the member cluster with 5k Nodes and 2w Pods consumes 40m CPU(cores) and 266Mi Memory(bytes).
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +From the preceding test results, the API Call Latency and Resource Distribute Latency meet the SLIs/SLOs above. And the resources consumed by the system during the whole process are in a controllable
```suggestion
From the preceding test results, the API Call Latency and Resource Distribution Latency meet the SLIs/SLOs above, and the resources consumed by the system during the whole process are in a controllable range.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +Therefore, **Karmada can stably support 100 clusters with 500000 nodes and more than two million pods**. In production, Karmada effectively supports the management of hundreds of huge clusters.
```suggestion
Therefore, **Karmada can stably support 100 clusters with 500,000 nodes and more than two million pods**. In production, Karmada effectively supports the management of hundreds of large-sized clusters.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +### Separation of Concerns: Resource Templates and Policies
```suggestion
### Separation of Concerns: Resource Templates and Policies
```
```suggestion
### Resource Templates and Policies
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +Karmada uses Kubernetes Native APIs for federated resource templates and reusable Policy APIs for cluster scheduling strategies. It not only makes it integrate with the Kubernetes ecosystem, but also
```suggestion
Karmada uses Kubernetes native APIs for federated resource templates and reusable Policy APIs for cluster scheduling strategies. These allow Karmada to integrate with the Kubernetes ecosystem and greatly reduce the number of resources on the control plane.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +Based on this, the number of resources for the control plane does not depend on how many clusters on the control plane, but depends on numbers of multi-cluster applications.
```suggestion
Based on this, the number of resources for the control plane does not depend on how many clusters on the control plane, but on how many multi-cluster applications.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +Now whether it is Push mode or Pull mode, we both can use the karmadactl CLI to complete the cluster registration. Compared with Push mode, there is a component named karmada-agent running on the mem
```suggestion
For both the Push and Pull modes, we can use the karmadactl CLI to complete cluster registration. Unlike the Push mode, the Pull mode runs a component named karmada-agent on member clusters.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +Cluster registry latency above contains the delay for the control plane to successfully collect the member cluster status. In the process of cluster lifecycle management, Karmada will collect the clu
```suggestion
Cluster registration latency contains the latency for the control plane to successfully collect the member cluster status. In the process of cluster lifecycle management, Karmada will collect the cluster version, API enablement and whether the cluster is online or healthy.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +Cluster registry latency above contains the delay for the control plane to successfully collect the member cluster status. In the process of cluster lifecycle management, Karmada will collect the clu
Cluster **Registry** Latency or Cluster **Registration** Latency, please choose one and use it in all the places it shows up.

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +Whether Push mode or Pull mode, Karmada maintains a fast rate for distributing resources to member clusters. The only difference is that karmada-controller-manager on the control plane is responsible
```suggestion
No matter whether you are using the Push mode or Pull mode, Karmada maintains a fast rate for distributing resources to member clusters. The only difference is that karmada-controller-manager on the control plane is responsible for the distribution of all cluster resources in Push mode whereas karmada-agent is only responsible for one cluster in Pull mode.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +### Resource Usage between Push mode and Pull mode
```suggestion
### Resource Usage between Push Mode and Pull Mode
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +In Karmada 1.3, we do a lot of work to reduce Karmada's resource consumption when managing huge clusters. Now we are happy to announce that compared with version 1.2, Karmada 1.3 reduces memory consu
```suggestion
In Karmada 1.3, we did a lot to reduce Karmada's resource consumption when managing large clusters. Compared with version 1.2, Karmada 1.3 reduces memory consumption by **85%** and CPU consumption by **32%** in large-scale scenarios.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +In Push mode, all requests come from karmada-controller-manager on the control plane.  You can configure `--kube-api-qps` and `--kube-api-burst` in karmada-controller-manager to control requests with
```suggestion
In Push mode, all requests come from karmada-controller-manager on the control plane. You can configure `--kube-api-qps` and `--kube-api-burst` in karmada-controller-manager to control requests within a certain threshold.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +Now Karmada provides the ability named [cluster resource modeling](https://karmada.io/docs/next/userguide/scheduling/cluster-resources) to make scheduling decisions in scenario of dynamic replica ass
```suggestion
Now Karmada provides the ability named [cluster resource modeling](https://karmada.io/docs/next/userguide/scheduling/cluster-resources) to make scheduling decisions in scenario of dynamic replica assignment based on idle cluster resources.
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +In terms of use scenarios, Push mode is suitable for managing Kubernetes clusters on public clouds, while Pull mode covers private cloud and edge-related scenarios compared to Push mode. In terms of
```suggestion
In terms of use scenarios, Push mode is suitable for managing Kubernetes clusters on public clouds, while Pull mode covers private cloud and edge-related scenarios. In terms of performance and security, the Pull mode outperforms the Push mode. 
```

2022-10-31 08:56 UTC, Tingtal commented on blog/2022-10-26-test-report/index.md
> +However, while the Pull mode improves performance, it also needs to correspondingly improve the performance of karmada-apiserver and karmada-etcd to face challenges in high-traffic and high-concurren
```suggestion
However, while the Pull mode improves performance, it also needs to correspondingly improve the performance of karmada-apiserver and karmada-etcd to face challenges in traffic-intensive and high-concurrency scenarios. For specific methods, please refer to the optimization of Kubernetes for large-scale clusters.
```

2022-11-01 03:33 UTC, Poor12 commented
/cc @RainbowMango

2022-11-01 03:40 UTC, RainbowMango commented
Please check and close the comments made by reviewers. And leave your comments on items that you don't agree with.

2022-11-01 03:44 UTC, Poor12 commented on blog/2022-10-26-test-report/index.md
> +The Karmada Controller Manager runs the various controllers,  the controllers watch Karmada objects and then talk to the underlying clusters' API servers to create regular Kubernetes resources.
Pasted from README.md in karmada.

2022-11-01 03:44 UTC, Poor12 commented
> Please check and close the comments made by reviewers. And leave your comments on items that you don't agree with.

Done

2022-11-01 03:52 UTC, RainbowMango commented on blog/2022-10-26-test-report/index.md
> +The Karmada Controller Manager runs the various controllers,  the controllers watch Karmada objects and then talk to the underlying clusters' API servers to create regular Kubernetes resources.
no big deal I guess.

2022-11-01 03:52 UTC, RainbowMango approved these changes
/lgtm
/approve

2022-11-01 03:53 UTC, merged