Add document for ClusterID
karmada-io/website pull request #222
Opened 2022-10-26 09:21 UTC by XiShanYongYe-Chang

Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Add document for [ClusterID](https://github.com/karmada-io/karmada/tree/master/docs/proposals/clusterid).

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

2022-10-26 09:22 UTC, XiShanYongYe-Chang commented
cc @Poor12 @yy158775 @RainbowMango

2022-10-26 09:27 UTC, Arhell reviewed
/assign @RainbowMango

2022-10-26 09:51 UTC, RainbowMango commented on docs/userguide/clustermanager/cluster-registration.md
> +Regardless of the mode of cluster, in the progress of registering the cluster into Karmada, we will set the `.spec.id` field, which is different from the object uid(.metadata.uid), to confirm the clu
Who is `we`?

2022-10-26 09:56 UTC, XiShanYongYe-Chang commented on docs/userguide/clustermanager/cluster-registration.md
> +Regardless of the mode of cluster, in the progress of registering the cluster into Karmada, we will set the `.spec.id` field, which is different from the object uid(.metadata.uid), to confirm the clu
the registering progress?

2022-10-27 13:06 UTC, RainbowMango commented
My suggestion:
```
Each cluster registered in Karmada will be represented as a `Cluster` object whose name(`.metadata.name`) is the 
registered name. The name will be widely used in the propagating process, such as specifying the location where a resource
should be propagated to in `PropagationPolicy`.

In addition, during the registration process, each cluster will be assigned a `unique identifier` which will be present at
the `.spec.id` of the `Cluster` object. For now, this `unique identifier` is used to distinguish each cluster technically 
to avoid accidentally registering the same cluster multiple times but using different register names.
The `unique identifier` is collected from the registering cluster's `kube-system` ID(`.metadata.uid`). 
```
Please @Tingtal take a look at this from a grammar point of view.

And please put this content at the end of this article, because people don't need to get involved before registering a cluster.

2022-10-27 13:12 UTC, XiShanYongYe-Chang commented
> My suggestion:
> 
> ```
> Each cluster registered in Karmada will be represented as a `Cluster` object whose name(`.metadata.name`) is the 
> registered name. The name will be widely used in the propagating process, such as specifying the location where a resource
> should be propagated to in `PropagationPolicy`.
> 
> In addition, during the registration process, each cluster will be assigned a `unique identifier` which will be present at
> the `.spec.id` of the `Cluster` object. For now, this `unique identifier` is used to distinguish each cluster technically 
> to avoid accidentally registering the same cluster multiple times but using different register names.
> The `unique identifier` is collected from the registering cluster's `kube-system` ID(`.metadata.uid`). 
> ```
> 
> Please @Tingtal take a look at this from a grammar point of view.
> 
> And please put this content at the end of this article, because people don't need to get involved before registering a cluster.

Thanks~
/cc @Tingtal

2022-10-29 06:02 UTC, Tingtal requested changes
Language check.

2022-10-29 06:02 UTC, Tingtal commented on i18n/zh/docusaurus-plugin-content-docs/current/userguide/clustermanager/cluster-registration.md
>  - Watch manifests from Karmada execution space(namespace, `karmada-es-<cluster name>`) and deploy to the cluster which serves for.
This line "Each `karmada-agent` serves for a cluster and take responsibility for:" should be changed to:
**Each `karmada-agent` serves a cluster and:**

Seems I dont have the edit permission. Pls make the change.

2022-10-29 08:44 UTC, XiShanYongYe-Chang commented
@Tingtal Thanks a lot~

2022-10-29 09:08 UTC, RainbowMango approved these changes
/lgtm
/approve

2022-10-29 09:08 UTC, merged