Add crd application tutorial
karmada-io/website pull request #254
Opened 2022-11-18 07:10 UTC by Poor12

Signed-off-by: Poor12 <shentiecheng@huawei.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add tutorial about how to propagate crd applications.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
None

2022-11-24 02:03 UTC, RainbowMango commented on docs/tutorials/crd-application.md
> +> Please refer to FAQ Difference between [PropagationPolicy and ClusterPropagationPolicy](https://github.com/karmada-io/karmada/blob/master/docs/frequently-asked-questions.md#what-is-the-difference-b
The link is broken.

2022-11-24 02:06 UTC, RainbowMango commented
/assign @Tingtal

2022-11-26 11:35 UTC, Tingtal requested changes
Several touches on wording

2022-11-26 11:35 UTC, Tingtal commented on docs/tutorials/crd-application.md
> +title: Propagate a CRD application by Karmada
```suggestion
title: Propagate a CRD application with Karmada
```

2022-11-26 11:35 UTC, Tingtal commented on docs/tutorials/crd-application.md
> +This guide will cover:
```suggestion
This section guides you to:
```

2022-11-26 11:35 UTC, Tingtal commented on docs/tutorials/crd-application.md
> +The following steps demonstrating how to propagate a [Guestbook](https://book.kubebuilder.io/quick-start.html#create-a-project) which is defined by CRD.
```suggestion
The following steps walk you through how to propagate a [Guestbook](https://book.kubebuilder.io/quick-start.html#create-a-project) defined by a CRD.
```

2022-11-26 11:35 UTC, Tingtal commented on i18n/zh/docusaurus-plugin-content-docs/current/tutorials/crd-application.md
> +title: Propagate a CRD application by Karmada
Sync the changes above. Thanks

2022-11-28 03:28 UTC, Poor12 commented
/assign @RainbowMango

2022-11-30 01:47 UTC, RainbowMango commented
Please solve the conflicts.

2022-11-30 02:54 UTC, RainbowMango approved these changes
/lgtm
/approve

2022-11-30 02:55 UTC, merged