Add tutorials about karmada-search
karmada-io/website pull request #257
Opened 2022-11-21 12:33 UTC by Poor12

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add tutorials about karmada-search

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
None

2022-11-24 09:46 UTC, Poor12 commented
/cc @XiShanYongYe-Chang

2022-11-26 09:55 UTC, Tingtal requested changes
Small touches on wording. Pls check.

2022-11-26 09:55 UTC, Tingtal commented on docs/contributor/contribute-docs.md
>  * You want to translate our existing English docs to Chinese. In this case, you need to modify the corresponding file content from <https://github.com/karmada-io/website/tree/main/i18n/zh/docusaurus-
```suggestion
* Translate existing English docs to Chinese. In this case, you need to modify the corresponding file content from <https://github.com/karmada-io/website/tree/main/i18n/zh/docusaurus-plugin-content-docs/current>. 
```

2022-11-26 09:55 UTC, Tingtal commented on docs/contributor/contribute-docs.md
> +* You want to contribute Chinese docs without English version. Any articles of any kind are welcomed. In this case, you can add articles and titles to the main directory first. Article content can be
```suggestion
* Submit Chinese docs without the English version. No limits on the topic or category. In this case, you can add an empty article and its title to the main directory first, and complete the rest later. 
```

2022-11-26 09:55 UTC, Tingtal commented on docs/tutorials/karmada-search.md
> +If you install Karmada by Helm, you can choose any of the following ways to install:
```suggestion
If you install Karmada by Helm, you can choose any of the following ways to install:
```
```suggestion
If you install Karmada by Helm, you can choose any of the following ways to install `karmada-search`:
```

2022-11-26 09:55 UTC, Tingtal commented on docs/tutorials/karmada-search.md
> +## Cache Deployment resources across multi-clusters
```suggestion
## Cache Deployment resources across clusters
```

2022-11-26 09:55 UTC, Tingtal commented on docs/tutorials/karmada-search.md
> +### 2. Test By Kubernetes API
```suggestion
### 2. Test using Kubernetes API
```

2022-11-26 09:55 UTC, Tingtal commented on docs/tutorials/karmada-search.md
> +You need to expose the web service to the host port so that you can visit the dashboard by http.
```suggestion
You need to expose the web service to the host port so that you can visit the dashboard by HTTP requrests.
```

2022-11-26 09:55 UTC, Tingtal commented on docs/tutorials/karmada-search.md
> +Now data of `Deployment` across member1 and member2 have uploaded to `OpenSearch`.
```suggestion
Now data of `Deployment` across member1 and member2 has been uploaded to `OpenSearch`. 
```

2022-11-26 09:55 UTC, Tingtal commented on docs/tutorials/karmada-search.md
> +You can experience multi-cloud search yourself by leveraging the search engine.
```suggestion
You can try multi-cloud search yourself by leveraging the search engine.
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +With the widespread use of multi-clusters, the administrator may deploy services on multiple clusters in order to provide service capabilities nearby.
```suggestion
Multicluster is becoming a common practice. It brings services closer to users.
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +At this time, it's usually inconvenient to obtain the Kubernetes resource information across multiple clusters.
```suggestion
But it also makes it hard to query Kubernetes resources across clusters.
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +Therefore, we need a caching layer and a search engine for Karmada to cache and search Kubernetes resources across multiple clusters.
```suggestion
Therefore, we need a caching layer and a search engine for Karmada to cache and search for Kubernetes resources across multiple clusters.
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +* Accelerates resource requests processing speed across regions
```suggestion
* Accelerate resource requests processing across regions.
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +* Provides a cross-cluster resource view
```suggestion
* Provide a cross-cluster resource view.
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +* Compatible with multiple Kubernetes resource versions
```suggestion
* Be compatible with multiple Kubernetes resource versions.
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +* Unified resource requests entries
```suggestion
* Unify resource request entries.
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +* Reduces API server pressure of member clusters
```suggestion
* Reduce API server pressure on member clusters.
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +* Compatible with a variety of search engines and databases
```suggestion
* Adapt to a variety of search engines and databases.
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +## Config the cache scope of resources
```suggestion
## Scope the caching
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +`.spec` field of `ResourceRegistry` represents the configuration of the cache scope.
```suggestion
`.spec` in `ResourceRegistry` defines the cache scope.
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +`TargetCluster` supports the config of the clusters where the cache system collect resource from.
```suggestion
`TargetCluster` means the cluster from which the cache system collects resources. 
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +`ResourceSelector` specifies the resource type that should be cached by `karmada-search`. It supports the config of `APIVersion`, `Kind` and `Namespace`.
```suggestion
`ResourceSelector` specifies the type of resources to be cached by `karmada-search`. Subfields are `APIVersion`, `Kind` and `Namespace`. 
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +`ResourceSelector` can be configured as follows which means deployments in `default` namespace are selected:
```suggestion
The following example `ResourceSelector` means Deployments in `default` namespace are targeted:
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +If the `namespace` field is empty, it means all namespaces are selected.
```suggestion
A null `namespace` field means all namespaces are targeted.
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +:::note
```suggestion
:::Notes:
```

2022-11-26 09:55 UTC, Tingtal commented on docs/userguide/globalview/global-search-for-resources.md
> +`BackendStore` specifies the location where to store cached items. By default, it will be stored in the memory of `karmada-search`.
```suggestion
`BackendStore` specifies the location to store cached items. Defaults to the memory of `karmada-search`.
```

2022-11-26 09:55 UTC, Tingtal commented on i18n/zh/docusaurus-plugin-content-docs/current/tutorials/karmada-search.md
> +This guide will cover:
The following is the same as above. Pls sync the changes.

2022-11-28 03:56 UTC, Poor12 commented
/cc @RainbowMango

2022-11-30 01:43 UTC, RainbowMango approved these changes
/lgtm
/approve

2022-11-30 01:45 UTC, merged