Add metrics and event docs
karmada-io/website pull request #260
Opened 2022-11-26 07:02 UTC by Poor12

Signed-off-by: Poor12 <shentiecheng@huawei.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add metrics and event docs

**Which issue(s) this PR fixes**:
Part of #258 

**Special notes for your reviewer**:
None

2022-11-26 12:15 UTC, Tingtal requested changes
Small touches on wording. Pls check.

2022-11-26 12:15 UTC, Tingtal commented on docs/reference/instrumentation/event.md
> +This page details the event that different Karmada components export.
```suggestion
This section details the events that different Karmada components export.
```

2022-11-26 12:15 UTC, Tingtal commented on docs/reference/instrumentation/event.md
> +You can obtain the event by `kubectl describe` the corresponding object.
```suggestion
You can obtain query events by running `kubectl describe` on the corresponding object.
```

2022-11-26 12:15 UTC, Tingtal commented on docs/reference/instrumentation/metrics.md
> +This page details the metrics that different Karmada components export.
```suggestion
This section details the metrics that different Karmada components export. 
```

2022-11-26 12:15 UTC, Tingtal commented on docs/reference/instrumentation/metrics.md
> +| e2e_scheduling_duration_seconds            | Histogram | E2e scheduling latency in seconds.                                |        | karmada-scheduler           |
```suggestion
| e2e_scheduling_duration_seconds            | Histogram | E2E scheduling latency in seconds.                                |        | karmada-scheduler           |
```

2022-11-26 12:15 UTC, Tingtal commented on docs/reference/instrumentation/metrics.md
> +| scheduling_algorithm_duration_seconds      | Histogram | Scheduling algorithm latency in seconds(exclude scale scheduler). |        | karmada-scheduler           |
```suggestion
| scheduling_algorithm_duration_seconds      | Histogram | Scheduling algorithm latency in seconds (excluding scale scheduler). |        | karmada-scheduler           |
```

2022-11-30 06:37 UTC, RainbowMango commented on docs/reference/instrumentation/event.md
> +| CreateExecutionSpaceFailed              | cluster                                                                                     | Warning | cluster-controller
```suggestion
| CreateExecutionSpaceFailed              | Cluster                                                                                     | Warning | cluster-controller                                                                                                        |
```

2022-11-30 06:37 UTC, RainbowMango commented on docs/reference/instrumentation/event.md
> +| ReflectStatusFailed                     | work                                                                                        | Warning | work-status-controller
```suggestion
| ReflectStatusFailed                     | Work                                                                                        | Warning | work-status-controller                                                                                                    |
```

2022-11-30 06:37 UTC, RainbowMango commented on docs/reference/instrumentation/event.md
> +| CleanupWorkFailed                       | resourceBinding<br/>clusterResourceBinding                                                  | Warning | binding-controller<br/>cluster-resource-binding-con
```suggestion
| CleanupWorkFailed                       | ResourceBinding<br/>ClusterResourceBinding                                                  | Warning | binding-controller<br/>cluster-resource-binding-controller                                                                |
```

2022-11-30 08:47 UTC, RainbowMango approved these changes
/lgtm
/approve

2022-11-30 08:47 UTC, merged