[zh]translate docs:migration-from-kubefed.md
karmada-io/website pull request #405
Opened 2023-07-03 06:44 UTC by justedennnnn

**What type of PR is this?**

/kind documentation

**Special notes for your reviewer**:

2023-07-07 00:06 UTC, windsonsea reviewed
Some terms like `override` and `propagation` will be clear if you can look up through the documents. Comments here are only for reference. Thanks.

2023-07-07 00:06 UTC, windsonsea commented on i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
> +参见[资源传播](https://karmada.io/docs/userguide/scheduling/resource-propagating)了解更多细节。
```suggestion
参见[资源调度](https://karmada.io/docs/userguide/scheduling/resource-propagating)了解更多细节。
```

2023-07-07 00:06 UTC, windsonsea commented on i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
> +对于 `override` 部分，Karmada 提供了 `OverridePolicy`  API 来保存区分的规则：
```suggestion
对于 `override` 部分，Karmada 提供了 `OverridePolicy` API 来保存差异化规则：
```

2023-07-07 00:06 UTC, windsonsea commented on i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
> +`OverridePolicy` 定义了哪些资源 (`resourceSelectors`) 在传播到 where（`targetCluster`）时应该被覆盖的规则传播到哪里（`targetCluster`）。
```suggestion
`OverridePolicy` 定义了哪些资源 (`resourceSelectors`) 在调度到哪里 (`targetCluster`) 时应该被覆盖的规则。
```

2023-07-07 00:06 UTC, windsonsea commented on i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
> +除了 Kubefed 之外，Karmada 还提供了各种替代方案来声明覆盖规则，见[Overriders](https://karmada.io/docs/userguide/scheduling/override-policy#overriders)了解更多细节。
```suggestion
除了 Kubefed 之外，Karmada 还提供了各种替代方案来声明差异化规则，参见
[Overrider](https://karmada.io/docs/userguide/scheduling/override-policy#overriders)了解更多细节。
```

2023-07-07 00:06 UTC, windsonsea commented on i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
> +我们还没有这个计划，因为我们接触了一些 Kubefed 用户，发现他们通常不使用 Vanilla Kubefed，而是分叉版本。
```suggestion
我们还没有这个计划，因为我们接触了一些 Kubefed 用户，发现他们通常不使用 Vanilla Kubefed，而是使用克隆版本。
```

2023-07-10 14:33 UTC, SAMZONG commented on i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
> +和[Federation V2(又名 Kubefed)](https://github.com/kubernetes-sigs/kubefed)。Karmada 继承了很多概念
```suggestion
Karmada 是在 Kubernetes [Federation V1](https://github.com/kubernetes-retired/federation)
和[Federation V2(又名 Kubefed)](https://github.com/kubernetes-sigs/kubefed)上开发的。Karmada 继承了很多两者的概念
```

2023-07-10 14:33 UTC, SAMZONG commented on i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
> +- **繁殖政策**：Karmada 提供独立的传播（位置）策略 API 来定义多集群调度和分布要求。
```suggestion
- **传播策略**：Karmada 提供独立的传播（位置）策略 API 来定义多集群调度和分布要求。
```
一般情况下，我们将 `Policy` 翻译为 策略，Propagation Policy 更合适称之为 传播策略， 你可以在很多 Karmada 的文章找到这部分.

2023-07-10 14:33 UTC, SAMZONG commented on i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
> +我们现在也在期待更多的反馈，请随时联系我们，我们很乐意支持您完成迁移工作。
```suggestion
我们非常期待更多的反馈，请随时与我们联系，我们将乐意支持您完成迁移工作。
```

2023-07-11 01:09 UTC, windsonsea requested changes
汗，这大部分都没改呀，怎么就点了 Resolve conversation 了？

2023-07-11 01:15 UTC, windsonsea commented
/hold until all comments are really resolved

2023-07-11 02:02 UTC, RainbowMango commented
@justedennnnn Can you help to resolve the conflicts, the typo in `docs/administrator/migration/migration-from-kubefed.md` has been resolved in #416.

2023-07-11 02:03 UTC, RainbowMango commented on i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
> +- **繁殖政策**：Karmada 提供独立的传播（位置）策略 API 来定义多集群调度和分布要求。
这里还是翻译成 `分发策略`吧。

2023-07-11 02:25 UTC, Poor12 reviewed
Please check again whether the previous review comments have been modified.

2023-07-11 02:25 UTC, Poor12 commented on i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
> +- **繁殖政策**：Karmada 提供独立的传播（位置）策略 API 来定义多集群调度和分布要求。
Propagation Policy 最好不要翻译成传播策略，传播这个词更多用于新闻与传媒相关的领域。如果在其他Karmada的文章中找到，我们最好一起修正下。

2023-07-11 02:32 UTC, justedennnnn commented on i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
> +- **繁殖政策**：Karmada 提供独立的传播（位置）策略 API 来定义多集群调度和分布要求。
ok

2023-07-11 02:34 UTC, justedennnnn commented
> /hold until all comments are really resolved

sorry，forget to save changes

2023-07-11 02:45 UTC, windsonsea commented
/unhold

2023-07-11 02:54 UTC, windsonsea reviewed
Thanks for your revising.

2023-07-11 02:54 UTC, windsonsea commented on i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
> +- **分发策略**：Karmada 提供独立的 Propagation(placement) Policy API 来定义多集群调度和分发要求。
这里 Propagation 用了`分发`，下文 Propagation 是不是也要相应修改的？

2023-07-11 02:54 UTC, windsonsea commented on i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
> +- **资源模版**：Karmada 使用 kubernetes 原生 API 定义用于联邦化的资源模板，使其易于与已采用 Kubernetes 的现有工具集成。
```suggestion
- **资源模板**：Karmada 使用 kubernetes 原生 API 定义用于联邦化的资源模板，使其易于与已采用 Kubernetes 的现有工具集成。
```

2023-07-11 02:54 UTC, windsonsea commented on i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
> +请参阅 [集群模式概述](https://karmada.io/docs/userguide/clustermanager/cluster-registration) 。
```suggestion
Kubefed 管理着 `PUSH` 模式的集群，但是 Karmada 支持 `PUSH` 和 `PULL` 两种模式。
请参阅[集群模式概述](https://karmada.io/docs/userguide/clustermanager/cluster-registration)。
```

2023-07-11 05:48 UTC, justedennnnn commented on i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
> +- **分发策略**：Karmada 提供独立的 Propagation(placement) Policy API 来定义多集群调度和分发要求。
Done

2023-07-11 06:11 UTC, windsonsea commented
Thanks.
/lgtm

2023-07-12 09:54 UTC, SAMZONG commented
I think it's all great.

/lgtm
/approve

Thanks for your contribution.

2023-07-12 10:10 UTC, justedennnnn commented
> I think it's all great.
> 
> /lgtm /approve
> 
> Thanks for your contribution.

Thanks for your review.

2023-07-12 10:12 UTC, justedennnnn commented
> @justedennnnn Can you help to resolve the conflicts, the typo in `docs/administrator/migration/migration-from-kubefed.md` has been resolved in #416.

Done

2023-07-12 10:22 UTC, RainbowMango approved these changes
/approve

2023-07-12 10:23 UTC, merged