[zh] translate docs: aggregated-api-endpoint.md
karmada-io/website pull request #412
Opened 2023-07-09 05:36 UTC by huan555

Add one of the following kinds:

/kind documentation

2023-07-09 09:23 UTC, windsonsea commented
Please run the following commands to add your signature:

```
git commit -s --amend
git push origin wh01 -f
```

2023-07-09 09:37 UTC, windsonsea commented on i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/globalview/aggregated-api-endpoint.md
> +新引入的 [karmada-aggregated-apiserver](https://github.com/karmada-io/karmada/blob/master/cmd/aggregated-apiserver/main.go) 组件将所有注册的集群合并在一起，允许用户通过 Karmada 的代理端点访问成员集群。
```suggestion
新引入的 [karmada-aggregated-apiserver](https://github.com/karmada-io/karmada/blob/master/cmd/aggregated-apiserver/main.go) 组件将所有注册的集群聚合在一起，允许用户通过代理端点使用 Karmada 访问成员集群。
```

2023-07-09 09:37 UTC, windsonsea commented on i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/globalview/aggregated-api-endpoint.md
> +### 步骤1：获取 karmada-apiserver 证书
```suggestion
### 步骤 1：获取 karmada-apiserver 证书
```

2023-07-09 09:37 UTC, windsonsea commented on i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/globalview/aggregated-api-endpoint.md
> +### 步骤2：授予用户 `system:admin` 权限
```suggestion
### 步骤 2：给用户 `system:admin` 授权
```

2023-07-09 09:37 UTC, windsonsea commented on i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/globalview/aggregated-api-endpoint.md
> +### 第3步：访问成员集群
```suggestion
### 步骤 3：访问成员集群
```

2023-07-09 09:37 UTC, windsonsea commented on i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/globalview/aggregated-api-endpoint.md
> +或者将 `/apis/cluster.karmada.io/v1alpha1/clusters/{clustername}/proxy` 添加到 karmada-apiserver.config 文件中的服务器地址中，您就可以直接使用：
```suggestion
或者将 `/apis/cluster.karmada.io/v1alpha1/clusters/{clustername}/proxy` 追加到 karmada-apiserver.config 的服务器地址，您就可以直接使用：
```

2023-07-09 09:37 UTC, windsonsea commented on i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/globalview/aggregated-api-endpoint.md
> +> 注意：对于以拉取模式加入 Karmada 的成员集群，并且仅允许集群对 Karmada 进行访问的情况，我们可以[部署 api-server-network-proxy（ANP）](../clustermanager/working-with-anp.md)来访问它。
```suggestion
> 注意：对于以拉取模式接入 Karmada 且仅允许从集群对 Karmada 进行访问的成员集群，我们可以[部署 api-server-network-proxy（ANP）](../clustermanager/working-with-anp.md)来访问它。
```

2023-07-10 02:57 UTC, windsonsea commented
No, something is still wrong to add your signature.

BTW, you need to squash your commits: 
https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits

2023-07-10 03:54 UTC, SAMZONG commented
pls, rebase you all commits to one commit, and make it be signed.

@huan555

2023-07-10 14:56 UTC, huan555 commented
> Please run the following commands to add your signature:
> 
> ```
> git commit -s --amend
> git push origin wh01 -f
> ```

I have tried these commands again

2023-07-11 01:12 UTC, windsonsea requested changes
对于所有的 comments，如果有异议，请提出；如果无异议，请复制粘贴。

需要重新检查一下所有 comments，看看是不是改对了

2023-07-11 01:14 UTC, windsonsea commented
/hold until the changes are compliant with suggestions.

2023-07-11 01:18 UTC, RainbowMango commented
> 对于所有的 comments，如果有异议，请提出；如果无异议，请复制粘贴。
> 
> 但你大部分没改，却点了 Resolve conversation，这是几个意思？？？

@windsonsea 
请注意 @huan555 是一位 `first-time-contributor`, 可能并不熟悉GitHub处理review意见的方式，作为reviewer，请耐心指导帮助贡献者完成整个贡献流程。

2023-07-11 01:20 UTC, RainbowMango reviewed
/unhold
/assign @Poor12 @XiShanYongYe-Chang 

@huan555 Thanks for doing this.

2023-07-11 01:27 UTC, RainbowMango commented on i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/globalview/aggregated-api-endpoint.md
我觉得可以翻译（修改）这篇文章：
```
https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md
```
而不是`version-v1.6`版本的文档。 文档翻译工作应该针对最新的`current`目录进行。

2023-07-11 01:30 UTC, RainbowMango commented
接下来请 `Aggregated Kubernetes API` feature 作者 @XiShanYongYe-Chang review 并帮助 @huan555 完成该PR。

2023-07-11 01:49 UTC, huan555 commented on i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/globalview/aggregated-api-endpoint.md
好的，我更新一下

2023-07-11 14:43 UTC, XiShanYongYe-Chang commented on i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md
> +title: 聚合 Kubernetes API 端点
之快二直译可能不太好理解，是不是可以修改为：`聚合层APIServer` 呢？

2023-07-11 14:46 UTC, XiShanYongYe-Chang commented on i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md
> +新引入的 [karmada-aggregated-apiserver](https://github.com/karmada-io/karmada/blob/master/cmd/aggregated-apiserver/main.go) 组件将所有注册的集群聚合在一起，允许用户通过代理端点使用 Karmada 访问成员集群。
...，允许用户通过 proxy 端点从 Karmada 控制面统一访问成员集群。

2023-07-11 14:49 UTC, XiShanYongYe-Chang commented on i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md
> +为了快速体验这个功能，我们尝试使用了 karmada-apiserver 证书。
...，我们尝试通过使用 `karmada-apiserver` 证书来进行访问。

2023-07-11 14:50 UTC, XiShanYongYe-Chang commented on i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md
> +应用以下 yaml 文件：
Apply 是kubectl是一个子命令，我们此处是不是可以考虑不翻译它呢？

2023-07-11 14:51 UTC, XiShanYongYe-Chang commented on i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md
> +或者将 `/apis/cluster.karmada.io/v1alpha1/clusters/{clustername}/proxy` 追加到 karmada-apiserver.config 的服务器地址，您就可以直接使用：
...，您就可以直接使用以下命令：

2023-07-11 14:52 UTC, XiShanYongYe-Chang commented on i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md
> +> 注意：注意：对于以拉取模式接入 Karmada 且仅允许从集群对 Karmada 进行访问的成员集群，我们可以[部署 api-server-network-proxy（ANP）](../clustermanager/working-with-anp.md)来访问它。
注意 重复了

2023-07-11 14:53 UTC, XiShanYongYe-Chang commented on i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md
> +> 注意：注意：对于以拉取模式接入 Karmada 且仅允许从集群对 Karmada 进行访问的成员集群，我们可以[部署 api-server-network-proxy（ANP）](../clustermanager/working-with-anp.md)来访问它。
`部署 api-server-network-proxy（ANP）` 请帮忙确认下对应的文件标题是否一致。

2023-07-12 01:30 UTC, SAMZONG commented
Get it done, I'm looking forward to the moment when the PR is merged.

2023-07-12 02:46 UTC, huan555 commented
> @huan555 十分感谢你的贡献 :)

感谢指导，在这个pr中受益匪浅

2023-07-12 02:48 UTC, huan555 commented on i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md
> +> 注意：注意：对于以拉取模式接入 Karmada 且仅允许从集群对 Karmada 进行访问的成员集群，我们可以[部署 api-server-network-proxy（ANP）](../clustermanager/working-with-anp.md)来访问它。
引用文当前标题为：Deploy apiserver-network-proxy (ANP) For Pull mode，已经修改。

2023-07-12 02:48 UTC, huan555 commented on i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md
> +或者将 `/apis/cluster.karmada.io/v1alpha1/clusters/{clustername}/proxy` 追加到 karmada-apiserver.config 的服务器地址，您就可以直接使用：
已更改，thx

2023-07-12 02:51 UTC, huan555 commented on i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md
> +应用以下 yaml 文件：
这里目前改为：执行以下 YAML 文件：
为了语句通顺，采用了执行这个词，避开Apply 。
YAML 这个词在google搜索中普遍使用大写，所以这里改为大写。

2023-07-12 02:51 UTC, huan555 commented on i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md
> +为了快速体验这个功能，我们尝试使用了 karmada-apiserver 证书。
已修改，thx

2023-07-12 03:21 UTC, XiShanYongYe-Chang commented
Thx, please sign off refer to https://github.com/karmada-io/website/pull/412/checks?check_run_id=14966276827
Other parts LGTM

2023-07-12 09:48 UTC, huan555 commented
> Thx, please sign off refer to https://github.com/karmada-io/website/pull/412/checks?check_run_id=14966276827 Other parts LGTM

OK, I've signed off this commit, thx

2023-07-13 01:40 UTC, windsonsea commented
> 

/lgtm

Happy to know that.

2023-07-18 03:33 UTC, RainbowMango commented on i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md
> -title: Aggregated Kubernetes API Endpoint
ping @XiShanYongYe-Chang

2023-07-18 03:43 UTC, XiShanYongYe-Chang commented on i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md
> -title: Aggregated Kubernetes API Endpoint
Sorry, I miss this comment.
+1 thanks

@huan555 Can you help update it?

2023-07-21 08:48 UTC, XiShanYongYe-Chang commented
Kindly ping @huan555

2023-07-23 01:04 UTC, RainbowMango approved these changes
/lgtm
/approve

We can fix the comments with another PR.

2023-07-23 01:05 UTC, merged